margin = 120
always_for_in = true
whitespace_ops_in_indices = true
remove_extra_newlines = true
import_to_using = true
short_to_long_function_def = true
force_long_function_def = true
always_use_return = true
whitespace_in_kwargs = false
format_docstrings = true
trailing_comma = true
